SELECT json_object(
  'dcb_events', (SELECT COUNT(*) FROM dcb_events),
  'dcb_event_ops', (SELECT COUNT(*) FROM dcb_event_ops),
  'serialized_dcb_allocator_bindings', (SELECT COUNT(*) FROM serialized_dcb_allocator_bindings),
  'serialized_dcb_event_arrivals', (SELECT COUNT(*) FROM serialized_dcb_event_arrivals),
  'serialized_dcb_lag_estimates', (SELECT COUNT(*) FROM serialized_dcb_lag_estimates),
  'serialized_dcb_pending_arrivals', (SELECT COUNT(*) FROM serialized_dcb_pending_arrivals),
  'serialized_dcb_inconsistency_findings', (SELECT COUNT(*) FROM serialized_dcb_inconsistency_findings),
  'serialized_dcb_delivery_incidents', (SELECT COUNT(*) FROM serialized_dcb_delivery_incidents),
  'serialized_dcb_projection_checkpoints', (SELECT COUNT(*) FROM serialized_dcb_projection_checkpoints),
  'serialized_dcb_wait_target_incidents', (SELECT COUNT(*) FROM serialized_dcb_wait_target_incidents),
  'serialized_dcb_source_partitions', (SELECT COUNT(*) FROM serialized_dcb_source_partitions),
  'serialized_dcb_global_memberships', (SELECT COUNT(*) FROM serialized_dcb_global_memberships),
  'serialized_dcb_global_receipts', (SELECT COUNT(*) FROM serialized_dcb_global_receipts),
  'serialized_dcb_completeness_scanner_health', (SELECT COUNT(*) FROM serialized_dcb_completeness_scanner_health),
  'serialized_dcb_completeness_findings', (SELECT COUNT(*) FROM serialized_dcb_completeness_findings),
  'serialized_dcb_safe_lane_health', (SELECT COUNT(*) FROM serialized_dcb_safe_lane_health),
  'serialized_dcb_live_poll_health', (SELECT COUNT(*) FROM serialized_dcb_live_poll_health),
  'serialized_dcb_safe_lane_history', (SELECT COUNT(*) FROM serialized_dcb_safe_lane_history),
  'serialized_dcb_hop_measurements', (SELECT COUNT(*) FROM serialized_dcb_hop_measurements),
  'serialized_dcb_hop_submeasurements', (SELECT COUNT(*) FROM serialized_dcb_hop_submeasurements),
  'serialized_dcb_unsafe_writer_boundaries', (SELECT COUNT(*) FROM serialized_dcb_unsafe_writer_boundaries)
) AS counts;
